# Generated by Django 3.2.8 on 2022-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0002_auto_20220210_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='review',
        ),
        migrations.RemoveField(
            model_name='memories',
            name='reviewBy',
        ),
        migrations.AlterField(
            model_name='memories',
            name='likes',
            field=models.IntegerField(default=0, editable=None, null=True),
        ),
        migrations.AlterField(
            model_name='memories',
            name='photo_taken_on_date',
            field=models.DateField(blank=True, null=True, verbose_name='photo taken on '),
        ),
    ]
