# Generated by Django 4.0.2 on 2022-09-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0058_sitedata_bio_link_sitedata_logo'),
        ('Gallary', '0009_remove_memories_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='author',
            field=models.CharField(default='Kiran J', max_length=100),
        ),
        migrations.AlterField(
            model_name='memories',
            name='photo_taken_on_tour',
            field=models.ForeignKey(default='unknown tour', null=True, on_delete=django.db.models.deletion.PROTECT, to='updates.updates'),
        ),
    ]
