# Generated by Django 4.0.2 on 2022-09-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0059_alter_bookslot_amount_alter_bookslot_slotfor_and_more'),
        ('Gallary', '0011_alter_memories_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='photo_taken_on_tour',
            field=models.ForeignKey(default='unknown tour', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='updates.updates'),
        ),
    ]
