# Generated by Django 4.1.1 on 2022-10-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0105_updates_aadhaar_required'),
        ('Gallary', '0016_alter_memories_photos_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='uploadede_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='memories',
            name='photo_taken_on_tour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='updates.updates'),
        ),
    ]
