# Generated by Django 4.1.1 on 2022-10-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0017_memories_uploadede_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memories',
            old_name='uploadede_on',
            new_name='uploaded_on',
        ),
    ]
