# Generated by Django 3.2.8 on 2022-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_taken_on_date', models.TimeField(blank=True, null=True, verbose_name='photo taken on ')),
            ],
        ),
    ]
