# Generated by Django 3.2.8 on 2022-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='likes',
            field=models.IntegerField(default=0, editable=None),
        ),
        migrations.AddField(
            model_name='memories',
            name='photo_taken_on_tour',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memories',
            name='photos_taken',
            field=models.ImageField(default=1, upload_to='media/Gallary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memories',
            name='review',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memories',
            name='reviewBy',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
