# Generated by Django 3.2.8 on 2022-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0003_auto_20220210_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='photo_taken_on_location_url',
            field=models.URLField(default=1, verbose_name='google map location url'),
            preserve_default=False,
        ),
    ]
