# Generated by Django 4.0.2 on 2022-08-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0005_alter_memories_photos_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
