# Generated by Django 4.0.2 on 2022-09-16 13:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0006_memories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='photos_taken',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[285, 160], upload_to='DataBase/Gallary/Images'),
        ),
    ]
