# Generated by Django 4.0.2 on 2022-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0007_alter_memories_photos_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='photos_taken',
            field=models.ImageField(upload_to='DataBase/Gallary/Images'),
        ),
    ]
