# Generated by Django 4.0.2 on 2022-09-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0008_alter_memories_photos_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='likes',
        ),
    ]
