# Generated by Django 4.0.2 on 2022-09-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0010_memories_author_alter_memories_photo_taken_on_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='author',
            field=models.CharField(default='kiran J', max_length=50, null=True, verbose_name='name or insta username of person who had taken this pic'),
        ),
    ]
