# Generated by Django 4.0.2 on 2022-09-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0013_alter_memories_photo_taken_on_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='photo_taken_on_date',
        ),
        migrations.RemoveField(
            model_name='memories',
            name='photo_taken_on_location_url',
        ),
    ]
