# Generated by Django 4.0.2 on 2022-09-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0014_remove_memories_photo_taken_on_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='description',
        ),
    ]
