# Generated by Django 4.0.2 on 2022-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallary', '0015_remove_memories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='photos_taken',
            field=models.ImageField(upload_to='Gallary/Images'),
        ),
    ]
