# Generated by Django 3.2.8 on 2022-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='date_added',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
