# Generated by Django 3.2.8 on 2022-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_updates_tumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='Review',
            field=models.TextField(verbose_name='what is Review'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='ReviewBy',
            field=models.CharField(max_length=25, verbose_name='review given by'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='ReviewerImage',
            field=models.ImageField(upload_to='media/Testimonials', verbose_name="reviewer's image"),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='profession',
            field=models.CharField(max_length=25, verbose_name='Profession Of reviewer'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='Heading',
            field=models.CharField(max_length=100, verbose_name='heading text'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='Tour_image',
            field=models.ImageField(upload_to='media/tour', verbose_name='tour image shown on cards.'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='Tumbnail',
            field=models.ImageField(upload_to='media/tour/tubnail', verbose_name='detailed thubnail'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='price',
            field=models.IntegerField(verbose_name='price Of tour'),
        ),
    ]
