# Generated by Django 3.2.8 on 2022-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_auto_20220211_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WPNumber', models.IntegerField()),
                ('SecondNumber', models.IntegerField()),
                ('Instagram_Profile_Link', models.URLField()),
                ('WP_Link', models.URLField()),
                ('Email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
