# Generated by Django 4.0.2 on 2022-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_sitedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('FullName', models.CharField(max_length=30)),
                ('Message', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
