# Generated by Django 4.0.2 on 2022-05-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0013_updates_tourexpire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='TourExpire',
        ),
    ]
