# Generated by Django 4.0.2 on 2022-05-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0015_updates_tourexpire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='TourExpire',
            new_name='TourIsNotExpire',
        ),
    ]
