# Generated by Django 4.0.2 on 2022-05-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0016_rename_tourexpire_updates_tourisnotexpire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='Phone_no2',
        ),
    ]
