# Generated by Django 4.0.2 on 2022-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0017_remove_bookslot_phone_no2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='TripId',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
