# Generated by Django 4.0.2 on 2022-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0023_alter_updates_tour_image_alter_updates_tumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='tour_from_to',
            field=models.CharField(default=1, max_length=50, verbose_name='Date of Tour: month Form_date - To_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updates',
            name='tour_on_date',
            field=models.DateField(verbose_name='Booking End on'),
        ),
    ]
