# Generated by Django 4.0.2 on 2022-08-08 08:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0025_alter_updates_tumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('About', models.CharField(max_length=250)),
                ('whatsapp', models.URLField()),
                ('instagram', models.URLField()),
                ('telephone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='organizers')),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='updates',
            name='Tour_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=100, scale=None, size=[375, 225], upload_to='tour', verbose_name='tour image shown on cards.'),
        ),
    ]
