# Generated by Django 4.0.2 on 2022-08-09 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0027_updates_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='updates',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='City Name of VENUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='district',
            field=models.CharField(default=1, max_length=50, verbose_name='District Name of VENUE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='googleMap',
            field=models.URLField(default=12, verbose_name='Google Map VENUE Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Tour will start on : Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='Tags',
            field=models.ManyToManyField(to='updates.Tags', verbose_name='Tags'),
        ),
    ]
