# Generated by Django 4.0.2 on 2022-08-10 11:23

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0029_remove_organizer_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter_Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscribed_on', models.DateField(auto_created=True, auto_now=True)),
                ('Email_Id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='updates',
            name='Tour_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=False, quality=100, scale=None, size=[375, 225], upload_to='media/tour', verbose_name='tour image shown on cards.'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='Tumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[800, 450], upload_to='media/tour/tubnail', verbose_name='detailed thubnail'),
        ),
    ]
