# Generated by Django 4.0.2 on 2022-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0032_bookslot_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='Payment_Status',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
