# Generated by Django 4.0.2 on 2022-08-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0034_bookslot_canceled_bookslot_canceled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='canceled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
