# Generated by Django 4.0.2 on 2022-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0038_remove_bookslot_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='canceled_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
