# Generated by Django 4.0.2 on 2022-08-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0039_bookslot_canceled_bookslot_canceled_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='canceled_on',
        ),
        migrations.CreateModel(
            name='Canceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Canceled_on', models.DateTimeField(auto_now=True)),
                ('TripId', models.CharField(editable=False, max_length=20)),
                ('Payment_id', models.CharField(editable=False, max_length=50, null=True)),
                ('Name', models.CharField(max_length=30)),
                ('Phone_no1', models.IntegerField()),
                ('email', models.EmailField(blank=True, default='null@gmail.com', max_length=254, null=True)),
                ('SlotWasFor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='updates.updates')),
            ],
        ),
    ]
