# Generated by Django 4.0.2 on 2022-08-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0045_rename_slotfor_refund_refund_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='Refund_Status',
            field=models.BooleanField(default=False),
        ),
    ]
