# Generated by Django 4.0.2 on 2022-08-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0046_refund_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='Refund_On',
            field=models.DateField(null='true'),
            preserve_default='true',
        ),
    ]
