# Generated by Django 4.0.2 on 2022-09-12 14:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0047_refund_refund_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='Heading', unique_with=['Organizer', 'tour_on_date']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='updates',
            name='Heading',
            field=models.CharField(max_length=50, verbose_name='heading text'),
        ),
    ]
