# Generated by Django 4.0.2 on 2022-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0049_remove_bookslot_id_alter_bookslot_tripid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='TripId',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
