# Generated by Django 4.0.2 on 2022-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0052_organizer_backgroundimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('template', models.FileField(upload_to='newsletter-mail_templates/')),
                ('template_name', models.CharField(max_length=50)),
            ],
        ),
    ]
