# Generated by Django 4.0.2 on 2022-09-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0054_alter_newsletter_templates_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter_Templates',
        ),
    ]
