# Generated by Django 4.0.2 on 2022-09-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0058_sitedata_bio_link_sitedata_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='amount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='slotFor',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='updates.updates'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='Organizer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='updates.organizer'),
        ),
    ]
