# Generated by Django 4.0.2 on 2022-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0060_alter_bookslot_slotfor_alter_updates_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='Booked_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
