# Generated by Django 4.0.2 on 2022-09-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0065_remove_bookslot_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='date_added',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
