# Generated by Django 4.0.2 on 2022-09-25 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0066_bookslot_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='TripId',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=20, unique=True),
        ),
    ]
