# Generated by Django 4.0.2 on 2022-09-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0069_alter_bookslot_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='razorpay_payment_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique_for_date=True),
        ),
    ]
