# Generated by Django 4.0.2 on 2022-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0073_remove_bookslot_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='date_added',
        ),
        migrations.AddField(
            model_name='bookslot',
            name='razorpay_payment_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
