# Generated by Django 4.0.2 on 2022-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0075_bookslot_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='date_added',
            field=models.DateTimeField(auto_created=True, default='10-5-2022', editable=False),
        ),
    ]
