# Generated by Django 4.0.2 on 2022-09-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0076_alter_bookslot_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='TripId',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='date_added',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
