# Generated by Django 4.1.1 on 2022-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0078_remove_bookslot_date_added_alter_bookslot_tripid'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='cancelation_Reason',
            field=models.CharField(default='no Reson where menstioned', max_length=50, null=True),
        ),
    ]
