# Generated by Django 4.1.1 on 2022-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0079_refund_cancelation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='cancelation_Reason',
            field=models.CharField(default='no reason where mentioned , default value saved', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='cancelation_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
