# Generated by Django 4.1.1 on 2022-10-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0082_alter_updates_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookslot',
            name='age',
            field=models.IntegerField(default=set),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='slotFor',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='updates.updates'),
        ),
    ]
