# Generated by Django 4.1.1 on 2022-10-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0083_bookslot_aadhaar_number_bookslot_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(editable=False),
        ),
    ]
