# Generated by Django 4.1.1 on 2022-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0087_remove_bookslot_aadhaar_number_remove_bookslot_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='razorpay_payment_id',
            field=models.CharField(default='payment_ID', editable=False, max_length=50, null=True),
        ),
    ]
