# Generated by Django 4.1.1 on 2022-10-02 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0095_remove_bookslot_birth_of_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='birth_of_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
