# Generated by Django 4.1.1 on 2022-10-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0101_alter_bookslot_birth_of_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='birth_of_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
