# Generated by Django 4.1.1 on 2022-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0102_alter_bookslot_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_tour',
            name='tansport_type',
            field=models.CharField(default='Non_Ac', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(editable=False),
        ),
    ]
