# Generated by Django 3.2.8 on 2022-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewBy', models.TextField()),
                ('Review', models.TextField()),
                ('ReviewerImage', models.ImageField(upload_to='media/Testimonials')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_added', models.DateTimeField(auto_created=True, auto_now=True)),
                ('Tour_image', models.ImageField(upload_to='media/tour')),
                ('Heading', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('tour_on_date', models.DateField()),
                ('slorts', models.IntegerField()),
                ('packageInfo', models.TextField()),
            ],
        ),
    ]
