# Generated by Django 3.2.8 on 2022-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_testimonials_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='profession',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='ReviewBy',
            field=models.CharField(max_length=25),
        ),
    ]
