# Generated by Django 3.2.8 on 2022-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_bookslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='Phone_no2',
            field=models.IntegerField(blank=True, default='00', null=True),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='email',
            field=models.EmailField(blank=True, default='null@gmail.com', max_length=254, null=True),
        ),
    ]
