# Generated by Django 4.0.2 on 2022-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0014_remove_updates_tourexpire'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='TourExpire',
            field=models.BooleanField(default=False),
        ),
    ]
