# Generated by Django 4.0.2 on 2022-06-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0018_bookslot_tripid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='TripId',
            field=models.CharField(max_length=20),
        ),
    ]
