# Generated by Django 4.0.2 on 2022-07-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0020_imageproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProduct',
            new_name='TourImages',
        ),
    ]
