# Generated by Django 4.0.2 on 2022-08-05 04:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0024_updates_tour_from_to_alter_updates_tour_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='Tumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=100, scale=None, size=[800, 450], upload_to='tour/tubnail', verbose_name='detailed thubnail'),
        ),
    ]
