# Generated by Django 4.0.2 on 2022-08-09 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0026_organizer_alter_updates_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='Organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='updates.organizer'),
            preserve_default=False,
        ),
    ]
