# Generated by Django 4.0.2 on 2022-08-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0028_tags_updates_city_updates_district_updates_googlemap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='tags',
        ),
    ]
