# Generated by Django 4.0.2 on 2022-08-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0040_remove_bookslot_canceled_remove_bookslot_canceled_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelation_date', models.DateField(auto_created=True, auto_now=True)),
                ('Name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=7)),
                ('TripId', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='null@gmail.com', max_length=254, null=True)),
                ('Phone_no1', models.IntegerField()),
                ('address', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('refund_Amount', models.IntegerField(default=0)),
                ('charge_Day', models.IntegerField()),
                ('charge_percenrate', models.IntegerField()),
                ('razorpay_payment_id', models.CharField(editable=False, max_length=50, null=True)),
                ('razorpay_order_id', models.CharField(editable=False, max_length=50, null=True)),
                ('razorpay_signature', models.CharField(editable=False, max_length=50, null=True)),
                ('Payment_Status', models.BooleanField(default=False)),
                ('slotFor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='updates.updates')),
            ],
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='Payment_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Canceled',
        ),
    ]
