# Generated by Django 4.0.2 on 2022-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0041_refund_alter_bookslot_payment_status_delete_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
