# Generated by Django 4.0.2 on 2022-08-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0042_refund_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReFund',
        ),
    ]
