# Generated by Django 4.0.2 on 2022-08-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0044_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='slotFor',
            new_name='ReFund_For',
        ),
    ]
