# Generated by Django 4.0.2 on 2022-09-21 05:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0051_alter_organizer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='backgroundImg',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format=None, keep_meta=False, quality=100, scale=None, size=[800, 450], upload_to='tours/Images/organizers/bg', verbose_name='Background Image'),
            preserve_default=False,
        ),
    ]
