# Generated by Django 4.0.2 on 2022-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0053_newsletter_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter_templates',
            name='template',
            field=models.FileField(upload_to='C:\\Users\\sid\\Desktop\\Django\\Source Code\\TrekTakes_Env\\SourceCode\\newsletter-mail_templates/'),
        ),
        migrations.AlterField(
            model_name='newsletter_templates',
            name='template_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
