# Generated by Django 4.0.2 on 2022-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0056_customize_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='customized_tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_on_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('group_size', models.IntegerField()),
                ('no_of_day', models.IntegerField()),
                ('start_date', models.DateField()),
                ('trek_name', models.CharField(max_length=50)),
                ('tour_explain', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='customize_tour',
        ),
    ]
