# Generated by Django 4.0.2 on 2022-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0057_customized_tour_delete_customize_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='bio_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='logo',
            field=models.ImageField(null=True, upload_to='siteData/logo'),
        ),
    ]
