# Generated by Django 4.0.2 on 2022-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0063_bookslot_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='date_added',
            field=models.DateTimeField(default='5'),
        ),
    ]
