# Generated by Django 4.0.2 on 2022-09-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0064_alter_bookslot_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='date_added',
        ),
    ]
