# Generated by Django 4.0.2 on 2022-09-25 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0068_alter_bookslot_tripid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='razorpay_payment_id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=50, null=True, unique_for_date=True),
        ),
    ]
