# Generated by Django 4.0.2 on 2022-09-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0072_alter_bookslot_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='razorpay_payment_id',
        ),
    ]
