# Generated by Django 4.1.1 on 2022-10-02 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0081_alter_updates_tourisnotexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='Organizer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='updates.organizer'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='TourIsNotExpire',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
