# Generated by Django 4.1.1 on 2022-10-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0088_alter_bookslot_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(default='not Avalable', editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='age',
            field=models.IntegerField(default='not Avalable'),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='TripId',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='razorpay_payment_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
