# Generated by Django 4.1.1 on 2022-10-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0089_bookslot_aadhaar_number_bookslot_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(default='5', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='age',
            field=models.IntegerField(default='5'),
        ),
    ]
