# Generated by Django 4.1.1 on 2022-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0090_alter_bookslot_aadhaar_number_alter_bookslot_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='age',
            field=models.IntegerField(),
        ),
    ]
