# Generated by Django 4.1.1 on 2022-10-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0091_alter_bookslot_aadhaar_number_alter_bookslot_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='bookslot',
            name='age',
        ),
    ]
