# Generated by Django 4.1.1 on 2022-10-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0092_remove_bookslot_aadhaar_number_remove_bookslot_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookslot',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
