# Generated by Django 4.1.1 on 2022-10-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0098_alter_bookslot_birth_of_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='age',
        ),
    ]
