# Generated by Django 4.1.1 on 2022-10-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0100_alter_bookslot_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='birth_of_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
