# Generated by Django 4.1.1 on 2022-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0103_customized_tour_tansport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='aadhaar_number',
            field=models.IntegerField(default='00000000000', editable=False, null=True),
        ),
    ]
