# Generated by Django 4.1.1 on 2022-10-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0104_alter_bookslot_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='aadhaar_required',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
